connector_type: google_cloud_pubsub
project_id: "{{ mage_secret_var('gcp_project_id_dev') }}"
topic_id: "{{ pubsub_topic_id }}"
subscription_id: eventarc-europe-west1-orchestration-testing-634019-sub-774
timeout: 5
batch_size: 100
pubsub_emulator_host: null  # "host.docker.internal:8085"
path_to_credentials_json_file: "/root/.ssh/google_credentials.json"
